# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/n1a-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter n1awifi n1a3g,$(TARGET_DEVICE)),)

endif
